services:
  - type: web
    name: restaurant-review-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: PLACE_ID
        value: central-park-boathouse-new-york-2
      - key: FLASK_ENV
        value: production